### ISSUE TITLE
redundant parts in universal build name

### ISSUE THREAD

**Issue by Andrej730** [ringsaturn/tzfpy#61]
Hi! I've noticed that mac build on pypi "tzfpy-0.15.5-cp312-cp312-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl" has redundant parts about _x86_64 and _arm64 architectures included in the name - when _universal2 by definition means that it has both those architectures.

pip itself is kind of clever about this and will automatically pick universal build if user requiested x86_64 or arm64 and only universal build is available, e.g. command below will work (quickfix-arm64 has only universal build too), so there shouldn't be a need to specify all architectures in the filename explicitly.

```
pip install quickfix-arm64 --platform macosx_11_5_arm64 --python-version 3.9 --implementation cp --only-binary=:all: --target=./site-packages
```

**Comment by ringsaturn** [comment]
Thanks for the feedback.

The file name of macOS whl file are generated by this GitHub Action step via maturin: https://github.com/ringsaturn/tzfpy/blob/v0.15.5/.github/workflows/CI.yml#L140-L157

```yaml
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: messense/maturin-action@v1
        with:
          command: build
          sccache: true
          args: --release -o dist --target universal2-apple-darwin -i 3.8 3.9 3.10 3.11 3.12
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos
          path: dist
```

Seems not an issue of tzfpy but of maturin?
